# Generated by Django 4.1.1 on 2022-09-07 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBuilderapi.builder')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('partType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBuilderapi.parttype')),
            ],
        ),
        migrations.CreateModel(
            name='BuildPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBuilderapi.build')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBuilderapi.part')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='builder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcBuilderapi.builder'),
        ),
    ]
